name: Java CI/CD
on:
  push:
    branches: ["main"]  
jobs:
  biuld:
   runs-on: ubuntu-latest
   steps:
    - name: chekout-code
      uses: actions/checkout@v4
    - name: set up Java
      uses: actions/setup-java@v4
      with:
       distribution: 'temurin'
       java-version: '17'
    - name: Compile java code
      run: javac App.java
    - name: Run Java Program
      run: java App
     
